package com.example.client_kurs.ui.theme

import androidx.compose.ui.graphics.Color

// Light theme
val md_theme_light_primary = Color(0xFF165A9A)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFD2E4FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001C37)
val md_theme_light_secondary = Color(0xFF4A607A)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD1E4FF)
val md_theme_light_onSecondaryContainer = Color(0xFF051D34)
val md_theme_light_tertiary = Color(0xFF006B62)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFF76F8EA)
val md_theme_light_onTertiaryContainer = Color(0xFF00201C)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF8F9FF)
val md_theme_light_onBackground = Color(0xFF191C20)
val md_theme_light_surface = Color(0xFFF8F9FF)
val md_theme_light_onSurface = Color(0xFF191C20)
val md_theme_light_surfaceVariant = Color(0xFFDEE3EB)
val md_theme_light_onSurfaceVariant = Color(0xFF42474E)
val md_theme_light_outline = Color(0xFF72777F)
val md_theme_light_inverseOnSurface = Color(0xFFF0F0F7)
val md_theme_light_inverseSurface = Color(0xFF2E3135)
val md_theme_light_inversePrimary = Color(0xFFA2C9FF)
val md_theme_light_surfaceTint = Color(0xFF165A9A)

// Dark theme
val md_theme_dark_primary = Color(0xFFA2C9FF)
val md_theme_dark_onPrimary = Color(0xFF00315C)
val md_theme_dark_primaryContainer = Color(0xFF004881)
val md_theme_dark_onPrimaryContainer = Color(0xFFD2E4FF)
val md_theme_dark_secondary = Color(0xFFB1C8E5)
val md_theme_dark_onSecondary = Color(0xFF1B3249)
val md_theme_dark_secondaryContainer = Color(0xFF324960)
val md_theme_dark_onSecondaryContainer = Color(0xFFD1E4FF)
val md_theme_dark_tertiary = Color(0xFF58DBCf)
val md_theme_dark_onTertiary = Color(0xFF003731)
val md_theme_dark_tertiaryContainer = Color(0xFF005048)
val md_theme_dark_onTertiaryContainer = Color(0xFF76F8EA)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF111418)
val md_theme_dark_onBackground = Color(0xFFE1E2E8)
val md_theme_dark_surface = Color(0xFF111418)
val md_theme_dark_onSurface = Color(0xFFE1E2E8)
val md_theme_dark_surfaceVariant = Color(0xFF42474E)
val md_theme_dark_onSurfaceVariant = Color(0xFFC2C7CF)
val md_theme_dark_outline = Color(0xFF8C9199)
val md_theme_dark_inverseOnSurface = Color(0xFF191C20)
val md_theme_dark_inverseSurface = Color(0xFFE1E2E8)
val md_theme_dark_inversePrimary = Color(0xFF165A9A)
val md_theme_dark_surfaceTint = Color(0xFFA2C9FF)